spring:
  application:
    name: Aether

  datasource:
    url: jdbc:postgresql://localhost:5432/testDB
    username: postgres
    password: Karan@2068k
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  ai:
    openai:
      api-key:
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: openai/gpt-5.2-codex
          temprature: 0.0
#jwt:
#  secret-key:
#
#stripe:
#  api:
#    secret:
#  webhook:
#    secret:

client.url: http://localhost:8080