spring:
  application:
    name: Aether

  datasource:
    url: jdbc:postgresql://localhost:9010/pgvector-test
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  ai:
    openai:
      api-key:
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.0
jwt:
  secret-key:

stripe:
  api:
    secret:
  webhook:
    secret:

client.url: http://localhost:8080

logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG
    org.springframework.security: DEBUG

minio:
  url: http://localhost:9000          # or minio:9000 if inside docker network
  access-key:
  secret-key:
  project-bucket:
